# Generated by Django 2.1.5 on 2019-02-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='li_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='membership_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='section',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='std_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='university_roll',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year',
        ),
    ]
