# Generated by Django 2.1.5 on 2019-02-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190225_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeaccess',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='main.Bike'),
        ),
        migrations.AlterField(
            model_name='bikeaccessrequest',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.Bike'),
        ),
        migrations.AlterField(
            model_name='ridesummary',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='main.Bike'),
        ),
    ]
